---
#
# Ansible managed
#
repository:
  description: Install and configure Consul CA on your system.
  homepage: https://buluma.github.io/
  topics: consul, ansible, molecule, tox, playbook, hacktoberfest
