- become: true
  gather_facts: false
  hosts: all
  name: Prepare
  roles:
  - role: buluma.bootstrap
  - role: buluma.ca_certificates
  - role: buluma.core_dependencies
  - go_version: 1.22.5
    role: buluma.go
  tasks:
  - ansible.builtin.command: go version
    changed_when: false
    environment:
      PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
    name: Verify that Go is installed and available in the $PATH.
